version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 4317:4317
      - 16686:16686
      - 14250:14250
    environment:
      - COLLECTOR_OTLP_ENABLED=true