spring:
  application:
    name: spring-telemetry
  jms:
    listener:
      max-concurrency: ${NUMBER_OF_CONSUMERS:5}
      min-concurrency: 1
  activemq:
    password: ${AMQ_PASSWORD:admin}
    user: ${AMQ_USER:admin}
    broker-url: ${AMQ_ADDRESS:tcp://localhost:61616}
    non-blocking-redelivery: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: ${spring.application.name}
    consumer:
      bootstrap-servers: localhost:29092
      autoOffsetReset: earliest
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.defers.springtelemetry.*"
management:
  tracing:
    sampling:
      probability: 1.0
#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
tracing:
#  url: http://localhost:4318/v1/traces #Jaeger endpoint
  url: http://localhost:4318/v1/traces #Tempo endpoint
app:
  remote-api:
    url: http://localhost:8090
  jms:
    queues:
      inbound: "user.in"
    redelivery:
      initial-redelivery-delay: 5000
      backoff-multiplier: 1.5
      maximum-redeliveries: -1
      maximum-redelivery-delay: 30000
  kafka:
    topics:
      inbound: "USER_IN"